# используем язык java. Travis CI поддерживает другие языки тоже.
language: java

jdk: openjdk12
# используем режим обычного пользователя для сборки проекта.
sudo: false

services:
- postgresql

before_install:
- psql -c 'create database tracker;' -U postgres

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
- bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту youremail@smtp.ru (изменить на свою), если сборка упала
notifications:
  email:
    recipients:
      quaresma_08@mail.ru
    on_success: never # default: change
    on_failure: always # default: always