# используем язык java. Travis CI поддерживает другие языки тоже.
language: java

jdk: openjdk12

addons:
  postgresql: "11"

# используем режим обычного пользователя для сборки проекта.
sudo: false

services:
- postgresql

before_script:
- psql -c "CREATE DATABASE tracker;" -U postgres
- psql -c "CREATE USER tester WITH PASSWORD 'password';" -U postgres
- psql -c "GRANT ALL PRIVILEGES ON DATABASE tracker TO tester;" -U postgres

# После выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
- bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту youremail@smtp.ru (изменить на свою), если сборка упала
notifications:
  email:
    recipients:
      quaresma_08@mail.ru
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    - CODECOV_TOKEN="bcf8f5fe-ccb2-428c-b883-7b4f96be5522"