language: java

jdk: openjdk12

services:
- postgresql

before_install:
- psql -c 'create database tracker;' -U postgres
- psql -c 'create database vacancy;' -U postgres

# После выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
- bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту youremail@smtp.ru (изменить на свою), если сборка упала
notifications:
  email:
    recipients:
      quaresma_08@mail.ru
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    - CODECOV_TOKEN="bcf8f5fe-ccb2-428c-b883-7b4f96be5522"